In [2]:
# importing all the necessary modules

import pandas as pd
import numpy as np

## Step 1: Analyzing the RAW data and understanding the data.

> **Note:** We might need to use MS Excel to understand the data

In [3]:
deaths = pd.read_csv('RAW_global_deaths.csv')
deaths.head()

,Country/Region,Province/State,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,Afghanistan,NaN,33.93911,67.709953,0,0,0,0,0,0,...,7896,7896,7896,7896,7896,7896,7896,7896,7896,7896
1,Albania,NaN,41.15330,20.168300,0,0,0,0,0,0,...,3598,3598,3598,3598,3598,3598,3598,3598,3598,3598
2,Algeria,NaN,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,Andorra,NaN,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,Angola,NaN,-11.20270,17.873900,0,0,0,0,0,0,...,1933,1933,1933,1933,1933,1933,1933,1933,1933,1933

In [4]:
deaths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Country/Region to 3/9/23
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.5+ MB

In [5]:
deaths.describe()

,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
count,287.000000,287.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,...,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02
mean,19.718719,22.182084,0.058824,0.062284,0.089965,0.145329,0.193772,0.283737,0.453287,0.460208,...,2.378091e+04,2.378707e+04,2.379249e+04,2.379697e+04,2.379793e+04,2.379844e+04,2.379971e+04,2.380290e+04,2.380790e+04,2.381246e+04
std,25.956609,77.870931,1.000000,1.001525,1.413797,2.353998,3.060245,4.471644,7.353103,7.353616,...,9.337339e+04,9.341836e+04,9.345110e+04,9.347703e+04,9.347884e+04,9.347810e+04,9.348106e+04,9.349767e+04,9.352985e+04,9.355567e+04
min,-71.949900,-178.116500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.072192,-32.823050,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01
50%,21.512583,20.939400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.440000e+02,9.440000e+02,9.520000e+02,9.520000e+02,9.520000e+02,9.520000e+02,9.520000e+02,9.520000e+02,9.520000e+02,9.520000e+02
75%,40.401784,89.224350,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,8.721000e+03,8.721000e+03,8.721000e+03,8.721000e+03,8.721000e+03,8.721000e+03,8.721000e+03,8.721000e+03,8.727000e+03,8.727000e+03
max,71.706900,178.065000,17.000000,17.000000,24.000000,40.000000,52.000000,76.000000,125.000000,125.000000,...,1.119917e+06,1.120897e+06,1.121658e+06,1.122165e+06,1.122172e+06,1.122134e+06,1.122181e+06,1.122516e+06,1.123246e+06,1.123836e+06

In [6]:
deaths.isnull().sum()

Country/Region      0
Province/State    198
Lat                 2
Long                2
1/22/20             0
                 ...
3/5/23              0
3/6/23              0
3/7/23              0
3/8/23              0
3/9/23              0
Length: 1147, dtype: int64

In [7]:
no_pos_data = [i for i in range(len(deaths)) if deaths.isnull().iloc[i, 2] and deaths.isnull().iloc[i, 3]]

# Task: Setting the values with the country's latitude and longitude values

# Step 1: Identify the data about these indexes
deaths.iloc[[53, 89], :]

,Country/Region,Province/State,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
53,Canada,Repatriated Travellers,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
89,China,Unknown,NaN,NaN,0,0,0,0,0,0,...,82195,82195,82195,82195,82195,82195,82195,82195,82195,82195

In [8]:
# Step 2: Since both countries have state/province values in the dataset, we can fill these values with either the above values or the values below.

# Note: If the country has no multiple state values, then we need to find the country's latitude and longitude values and then put them in the dataset.

deaths.iloc[:, 2:4] = deaths.iloc[:, 2:4].ffill()

In [9]:
deaths.duplicated().sum()

np.int64(0)

## Step 2: After analyzing, the conclusion is that it needed to be converted and pre-processed for better representation.

### Step 2.1: Transposing the dataset, as we need all columns as rows and rows as columns.

In [10]:
deaths = deaths.transpose()
deaths

,0,1,2,3,4,5,6,7,8,9,...,279,280,281,282,283,284,285,286,287,288
Country/Region,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,Australia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
Province/State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Australian Capital Territory,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lat,33.93911,41.1533,28.0339,42.5063,-11.2027,-71.9499,17.0608,-38.4161,40.0691,-35.4735,...,-32.5228,41.377491,-15.3767,6.4238,14.058324,31.9522,39.9042,15.552727,-13.133897,-19.015438
Long,67.709953,20.1683,1.6596,1.5218,17.8739,23.347,-61.7964,-63.6167,45.0382,149.0124,...,-55.7658,64.585262,166.9592,-66.5897,108.277199,35.2332,116.4074,48.516388,27.849332,29.154857
1/22/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3/5/23,7896,3598,6881,165,1933,0,146,130463,8721,228,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
3/6/23,7896,3598,6881,165,1933,0,146,130472,8721,228,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
3/7/23,7896,3598,6881,165,1933,0,146,130472,8721,228,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
3/8/23,7896,3598,6881,165,1933,0,146,130472,8727,228,...,7617,1637,14,5854,43186,5708,0,2159,4057,5671
3/9/23,7896,3598,6881,165,1933,0,146,130472,8727,228,...,7617,1637,14,5854,43186,5708,0,2159,4057,5671

## Renaming the index values for better readability and code writing.

In [11]:
# renaming the 'Country/Region' and 'Province/State'

deaths = deaths.rename(index={
    'Country/Region': 'Country',
    'Province/State': 'State'
})

### Step 2.2: Make a dictionary for all the countries that have data values spreaded in the different states, so we can identify and combine them under the country name. 

### This code analyzes a dataset (`cases`) where **countries and their states/provinces are stored across columns** rather than in a traditional tabular format.  

### Its main goal is to **identify which countries have state-level data** and to **group all corresponding state columns under each country**.

In [12]:
# Making a dictionary for all the countries that have states mentioned in the dataset.
# This dictionary will be used for removing the state row and combining the data in the country column
def stateFinder(deaths):

    # Finding the index of the states whose value is not null.
    notna_indexes = [i for i in deaths.columns if pd.notna(deaths.iloc[1, i])]
    
    countryWithStates = {}
    for i in notna_indexes:
        Country = deaths.iloc[0, i]
        States = []
        for j in deaths.columns:
            if Country == deaths.iloc[0, j]:
                States.append(j)
        countryWithStates.update({Country: States})

    return countryWithStates

cws_d = stateFinder(deaths)
for key, values in cws_d.items():
    print(f"{key} : {values}")

Australia : [9, 10, 11, 12, 13, 14, 15, 16]
Canada : [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]
China : [59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]
Denmark : [103, 104, 105]
France : [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]
Netherlands : [196, 197, 198, 199, 200]
New Zealand : [201, 202, 203]
United Kingdom : [264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278]

In [13]:
deaths.iloc[0,:].value_counts().head(10)

Country
China             34
Canada            16
United Kingdom    15
France            12
Australia          8
Netherlands        5
New Zealand        3
Denmark            3
Albania            1
Armenia            1
Name: count, dtype: int64

### Step 2.3: Now, we can combine all the states' data for each country.

### When aggregating data by country, geographic coordinates (latitude and longitude) are averaged, while all other numeric fields are summed to produce a single consolidated country-level record.

In [14]:
deaths.drop('State', axis=0, inplace=True)

In [15]:
for country, states in cws_d.items():
    position = deaths.iloc[1:3, states].mean(axis=1)
    total = deaths.iloc[3:, states].sum(axis=1)
    final = pd.concat([position, total])
    deaths.iloc[1:, states[0]] = final

for country, states in cws_d.items():
    deaths.drop(states[1:], axis=1, inplace=True)

In [16]:
# Make the country name a column name and drop the country row.
deaths.columns = deaths.iloc[0]
deaths.drop('Country', axis=0, inplace=True)

In [17]:
# Assign column and index names, for better understanding
# deaths.columns.name = 'Countries'
# deaths.index.name = 'Attributes'

In [18]:
# Temp code: Analyzing the combied data for validation.
countries = list(cws_d.keys())
deaths.loc[:, countries]

Country,Australia,Canada,China,Denmark,France,Netherlands,New Zealand,United Kingdom
Lat,-32.106275,47.612219,32.8525,63.2878,6.4253,21.40884,-27.0639,22.42456
Long,141.355487,-79.759187,111.089121,-13.3381,-9.839634,-52.99206,-51.5863,-42.022004
1/22/20,0,0,17,0,0,0,0,0
1/23/20,0,0,18,0,0,0,0,0
1/24/20,0,0,26,0,0,0,0,0
...,...,...,...,...,...,...,...,...
3/5/23,19459,51555,101054,8323,166071,23705,2550,220721
3/6/23,19459,51592,101055,8333,166114,23705,2550,220721
3/7/23,19459,51605,101055,8334,166138,23705,2550,220721
3/8/23,19459,51634,101055,8341,166165,23705,2550,220721
3/9/23,19574,51720,101056,8345,166176,23705,2550,220721

In [24]:
# deaths.reset_index(inplace=True)
deaths.index.name = None
deaths.columns.name = None
# deaths = deaths.rename(columns={'index':'Date'})
deaths

,Date,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
0,Lat,33.93911,41.1533,28.0339,42.5063,-11.2027,-71.9499,17.0608,-38.4161,40.0691,...,-32.5228,41.377491,-15.3767,6.4238,14.058324,31.9522,39.9042,15.552727,-13.133897,-19.015438
1,Long,67.709953,20.1683,1.6596,1.5218,17.8739,23.347,-61.7964,-63.6167,45.0382,...,-55.7658,64.585262,166.9592,-66.5897,108.277199,35.2332,116.4074,48.516388,27.849332,29.154857
2,1/22/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1/23/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1/24/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,3/5/23,7896,3598,6881,165,1933,0,146,130463,8721,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
1141,3/6/23,7896,3598,6881,165,1933,0,146,130472,8721,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
1142,3/7/23,7896,3598,6881,165,1933,0,146,130472,8721,...,7617,1637,14,5854,43186,5708,0,2159,4057,5668
1143,3/8/23,7896,3598,6881,165,1933,0,146,130472,8727,...,7617,1637,14,5854,43186,5708,0,2159,4057,5671
1144,3/9/23,7896,3598,6881,165,1933,0,146,130472,8727,...,7617,1637,14,5854,43186,5708,0,2159,4057,5671

In [25]:
def parse_date(date):
    if pd.isna(date):
        return pd.NaT

    date = str(date).strip()

    if '/' in date:
        return pd.to_datetime(date, format="%m/%d/%y", errors="coerce")
    elif '-' in date:
        return pd.to_datetime(date, format="%m-%d-%Y", errors="coerce")
    else:
        return pd.NaT


deaths.iloc[2:, 0] = deaths.iloc[2:, 0].apply(parse_date).dt.strftime("%d-%m-%Y")

deaths['Date']

0              Lat
1             Long
2       22-01-2020
3       23-01-2020
4       24-01-2020
           ...
1140    05-03-2023
1141    06-03-2023
1142    07-03-2023
1143    08-03-2023
1144    09-03-2023
Name: Date, Length: 1145, dtype: object

In [26]:
# Selecting the list of countries for the visualization task.

# countries = ['India', 'Australia', 'China', 'Japan', 'Canada', 'US', 'United Kingdom', 'United Arab Emirates', 'Germany', 'France', 'Russia', 'Singapore', 'New Zealand']

deaths.to_csv('Covid_19_Deaths_Cleaned.csv')